In [2]:
height_in=[74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]


In [2]:
import numpy as np

In [5]:
ar=np.array(height_in)

In [6]:
ar

array([74, 74, 72, ..., 75, 75, 73])

In [7]:
ar.size

1015

In [8]:
a=ar[:27]

In [9]:
a.size

27

In [10]:
a=a.reshape(3,9)

In [11]:
a

array([[74, 74, 72, 72, 73, 69, 69, 71, 76],
       [71, 73, 73, 74, 74, 69, 70, 73, 75],
       [78, 79, 76, 74, 76, 72, 71, 75, 77]])

In [13]:
a[:2,3:5]=99

In [14]:
a

array([[74, 74, 72, 99, 99, 69, 69, 71, 76],
       [71, 73, 73, 99, 99, 69, 70, 73, 75],
       [78, 79, 76, 74, 76, 72, 71, 75, 77]])

In [15]:
a>71

array([[ True,  True,  True,  True,  True, False, False, False,  True],
       [False,  True,  True,  True,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True]])

In [16]:
a[a>71]

array([74, 74, 72, 99, 99, 76, 73, 73, 99, 99, 73, 75, 78, 79, 76, 74, 76,
       72, 75, 77])

In [17]:
a

array([[74, 74, 72, 99, 99, 69, 69, 71, 76],
       [71, 73, 73, 99, 99, 69, 70, 73, 75],
       [78, 79, 76, 74, 76, 72, 71, 75, 77]])

In [18]:
a*1

array([[74, 74, 72, 99, 99, 69, 69, 71, 76],
       [71, 73, 73, 99, 99, 69, 70, 73, 75],
       [78, 79, 76, 74, 76, 72, 71, 75, 77]])

In [19]:
a/2

array([[37. , 37. , 36. , 49.5, 49.5, 34.5, 34.5, 35.5, 38. ],
       [35.5, 36.5, 36.5, 49.5, 49.5, 34.5, 35. , 36.5, 37.5],
       [39. , 39.5, 38. , 37. , 38. , 36. , 35.5, 37.5, 38.5]])

In [20]:
a*2

array([[148, 148, 144, 198, 198, 138, 138, 142, 152],
       [142, 146, 146, 198, 198, 138, 140, 146, 150],
       [156, 158, 152, 148, 152, 144, 142, 150, 154]])

In [21]:
a

array([[74, 74, 72, 99, 99, 69, 69, 71, 76],
       [71, 73, 73, 99, 99, 69, 70, 73, 75],
       [78, 79, 76, 74, 76, 72, 71, 75, 77]])

In [33]:
b=np.random.randint(1,50,(10,3))

In [34]:
b

array([[22, 39, 33],
       [ 2,  6,  1],
       [11, 10,  5],
       [ 5, 37, 19],
       [21, 29, 48],
       [ 8,  3, 43],
       [37, 22, 48],
       [48, 41, 16],
       [36, 16, 43],
       [12,  1, 29]])

In [50]:
a=np.array([True,1,2])

In [51]:
b=np.array([3,4,False])

In [52]:
c=a+b

In [53]:
print(c)

[4 5 2]


In [42]:
a=np.array([0,1,2])

In [43]:
b=np.array([3,4,0])

In [44]:
c=a+b

In [45]:
c

array([3, 5, 2])

In [54]:
np.array([True,1,2])+np.array([3,4,False])

array([4, 5, 2])

In [63]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [68]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.random.rand(10)

array([0.27767937, 0.75851994, 0.23094288, 0.41362181, 0.5237933 ,
       0.52452026, 0.70342821, 0.69209717, 0.67814123, 0.76383189])

In [73]:
np.random.rand(3,5)

array([[0.69659776, 0.83874103, 0.55266249, 0.7092561 , 0.41647323],
       [0.55838368, 0.36349118, 0.65550352, 0.88403257, 0.22653614],
       [0.65184447, 0.05611899, 0.45134762, 0.29197771, 0.33371145]])

In [76]:
np.random.randn(3,10)

array([[ 2.17618944,  0.25926808, -0.01802483,  0.38446403, -1.59851519,
        -0.27330036, -0.20796432, -1.01046443,  0.28934817,  0.30287087],
       [ 0.94487393, -0.65403527,  0.51732319,  0.15453956,  0.77077266,
         0.81430706,  1.57418241,  0.40843889, -0.5683451 , -0.00694815],
       [-1.98646783, -0.24219809, -0.6950244 ,  0.2032144 ,  0.21496421,
        -0.31985983, -1.49961218, -0.43152585, -0.14678937, -1.23731299]])

In [90]:
np.random.randint(-100,50,[3,3])

array([[ -1,   0,  43],
       [-67, -47,  30],
       [-92, -83,   7]])

In [94]:
a=np.arange(1,26)

In [95]:
a.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
b=a.tolist()

In [ ]:
type(b)

In [ ]:
np.linspace(1,50,50)

In [7]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])